package com.normuradov.ajva.utils

import org.junit.Assert.assertEquals
import org.junit.Test

class TransliterationTest {
    @Test
    fun testTransliterate() {
        val wordPairs = arrayOf(
            Pair("kitob", "китоб"),
            Pair("salom", "салом"),
            Pair("mehmon", "меҳмон"),
            Pair("hayot", "ҳаёт"),
            Pair("bola", "бола"),
            Pair("ish", "иш"),
            Pair("tosh", "тош"),
            Pair("olma", "олма"),
            Pair("soat", "соат"),
            Pair("qalam", "қалам"),
            Pair("taom", "таом"),
            Pair("o'y", "ўй"),
            Pair("dorixona", "дорихона"),
            Pair("chaqaloq", "чақалоқ"),
            Pair("yurt", "юрт"),
            Pair("qo'rg'on", "қўрғон"),
            Pair("suv", "сув"),
            Pair("shahar", "шаҳар"),
            Pair("o'zbekcha", "ўзбекча"),
            Pair("tarjima", "таржима"),
            Pair("ishonmoq", "ишонмоқ"),
            Pair("kelajak", "келажак"),
            Pair("qon", "қон"),
            Pair("o'qituvchi", "ўқитувчи"),
            Pair("universitet", "университет"),
            Pair("bilim", "билим"),
            Pair("o'quvchi", "ўқувчи"),
            Pair("xalq", "халқ"),
            Pair("yosh", "ёш"),
            Pair("yangilik", "янгилик"),
            Pair("qizil", "қизил"),
            Pair("tug'ilgan", "туғилган"),
            Pair("qarz", "қарз"),
            Pair("ishchi", "ишчи"),
            Pair("boshqaruv", "бошқарув"),
            Pair("chiroyli", "чиройли"),
            Pair("xorazm", "хоразм"),
            Pair("ko'ngil", "кўнгил"),
            Pair("mustaqil", "мустақил"),
            Pair("do'st", "дўст"),
            Pair("qarz", "қарз"),
            Pair("qurilma", "қурилма"),
            Pair("yil", "йил"),
            Pair("jamiyat", "жамият"),
            Pair("madaniyat", "маданият"),
            Pair("so'z", "сўз"),
            Pair("qora", "қора"),
            Pair("zamonaviy", "замонавий"),
            Pair("qiz", "қиз"),
            Pair("erkak", "эркак"),
            Pair("tabiat", "табиат"),
            Pair("mehmonxona", "меҳмонхона"),
            Pair("jahon", "жаҳон"),
            Pair("tadbir", "тадбир"),
            Pair("boy", "бой"),
            Pair("yordam", "ёрдам"),
            Pair("hamyon", "ҳамён"),
            Pair("ijod", "ижод"),
            Pair("osh", "ош"),
            Pair("qish", "қиш"),
            Pair("ajdaho", "аждаҳо"),
            Pair("huquq", "ҳуқуқ"),
            Pair("kelin", "келин"),
            Pair("erk", "эрк"),
            Pair("manzil", "манзил"),
            Pair("yulduz", "юлдуз"),
            Pair("qadriyat", "қадрият"),
            Pair("dengiz", "денгиз"),
            Pair("mantiq", "мантиқ"),
            Pair("bahor", "баҳор"),
            Pair("o'zbekiston", "ўзбекистон"),
            Pair("dunyo", "дунё"),
            Pair("valyuta", "валюта"),
            Pair("tarix", "тарих"),
            Pair("til", "тил"),
            Pair("ma'lumot", "ма'лумот"),
            Pair("g'isht", "ғишт"),
            Pair("yuqori", "юқори"),
            Pair("ixlosmand", "ихлосманд"),
            Pair("hurmat", "ҳурмат"),
            Pair("nafrat", "нафрат"),
            Pair("bahrom", "баҳром"),
            Pair("ro'yhat", "рўйҳат"),
            Pair("maftun", "мафтун"),
            Pair("qalb", "қалб"),
            Pair("zamin", "замин"),
            Pair("ozodlik", "озодлик"),
            Pair("ishora", "ишора"),
            Pair("oyin", "ойин"),
            Pair("nur", "нур"),
            Pair("farzand", "фарзанд"),
            Pair("vatan", "ватан"),
            Pair("mehnat", "меҳнат"),
            Pair("ayol", "аёл"),
            Pair("shifokor", "шифокор"),
            Pair("adabiyot", "адабиёт"),
            Pair("salomatlik", "саломатлик"),
            Pair("muhim", "муҳим"),
            Pair("e'tibor", "э'тибор"), // TODO: analyse this could be a bug
            Pair("baqir", "бақир"),
            Pair("aholi", "аҳоли"),
            Pair("ishbilarmon", "ишбилармон"),
            Pair("huquqiy", "ҳуқуқий"),
            Pair("istiqbol", "истиқбол"),
            Pair("do'stim", "дўстим"),
            Pair("qiziqarli", "қизиқарли"),
            Pair("ajablanarli", "ажабланарли"),
            Pair("qiyinchilik", "қийинчилик"),
            Pair("nishon", "нишон"),
            Pair("tajriba", "тажриба"),
            Pair("o'tgan", "ўтган"),
            Pair("qonli", "қонли"),
            Pair("sochi", "сочи"),
            Pair("bayram", "байрам"),
            Pair("xabar", "хабар"),
            Pair("ezgu", "эзгу"),
            Pair("buyuk", "буюк"),
            Pair("sadoqat", "садоқат"),
            Pair("himmat", "ҳиммат"),
            Pair("ijtimoiy", "ижтимоий"),
            Pair("qiziqish", "қизиқиш"),
            Pair("jonli", "жонли"),
            Pair("ijro", "ижро"),
            Pair("boylik", "бойлик"),
            Pair("yoshlar", "ёшлар")
        )

        for (pair in wordPairs) {
            val input = pair.first
            val expectedOutput = pair.second
            val result = transliterate(input)
            assertEquals(expectedOutput, result)
        }
    }
}